title: Bhavya Shah
logo: "/assets/photo.jpg" # Path to your photo
description: > # Adjusted to fix HTML and line breaks
  <strong style="color: black;">Data Analytics and Engineering</strong>
  <br><br>
  <a href="mailto:shahbhavya2021@gmail.com">Email</a>
  <br>
  <a href="https://linkedin.com/in/bhavya-ashvin-shah/">LinkedIn</a>
theme: jekyll-theme-minimal
